vim.cmd("set tabstop=2")
vim.cmd("set expandtab")
vim.cmd("set number")
vim.cmd("set shiftwidth=2")
vim.cmd("set relativenumber")
vim.cmd("set softtabstop=2")
vim.cmd("set noswapfile")
vim.g.mapleader = " "
vim.keymap.set("n", "<leader>vs", ":vsp <CR>", {})
vim.keymap.set("n", "<leader>v", ":sp <CR>", {})
vim.keymap.set("n", "Q", ":qa <CR>", {})
vim.keymap.set("n", "gV", ":vertical all <CR>", {})
